version: "3.9"

services:
  angular-frontend:
    build: /carpark-app
    working_dir: /app/carpark-app
    ports:
      - "4200:80"
    depends_on:
      - node-backend

  node-backend:
    build: /backend
    working_dir: /app/backend
    depends_on:
      - db
    ports:
      - "3000:3000"

